'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SnippetResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BG3_Horns_Code_Generator.SnippetResources", GetType(SnippetResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property Box_with_files() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Box_with_files", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;save&gt;
        '''&lt;version major=&quot;4&quot; minor=&quot;0&quot; revision=&quot;8&quot; build=&quot;503&quot;/&gt;
        '''    &lt;region id=&quot;CharacterCreationAppearanceVisuals&quot;&gt;
        '''        &lt;node id=&quot;root&quot;&gt;
        '''            &lt;children&gt;
        '''
        '''            CCAV_SNIPPET
        '''				
        '''            &lt;/children&gt;
        '''        &lt;/node&gt;
        '''  &lt;/region&gt;
        '''&lt;/save&gt;.
        '''</summary>
        Friend Shared ReadOnly Property CCAVFileInput() As String
            Get
                Return ResourceManager.GetString("CCAVFileInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to             &lt;!-- ======== NAME_HANDLE ========== --&gt;
        '''            &lt;node id=&quot;CharacterCreationAppearanceVisual&quot;&gt;
        '''			&lt;!-- Default/Standard bodyshape = 0, alternate/Strong bodyshape = 1 --&gt;
        '''                    &lt;attribute id=&quot;BodyShape&quot; type=&quot;uint8&quot; value=&quot;B_SHAPE&quot;/&gt;
        '''			&lt;!-- Masc = 0 , Fem = 1 --&gt;
        '''                    &lt;attribute id=&quot;BodyType&quot; type=&quot;uint8&quot; value=&quot;B_TYPE&quot;/&gt;
        '''			&lt;!-- This matches the .loca file that stores the names --&gt;
        '''                    &lt;attribute id=&quot;DisplayName&quot; type=&quot;TranslatedString&quot; ha [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property CCVASnippetInput() As String
            Get
                Return ResourceManager.GetString("CCVASnippetInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;contentList&gt;
        '''			&lt;!-- Stores localized names as UUID handles --&gt;
        '''	LOCA_SNIPPET
        '''&lt;/contentList&gt;.
        '''</summary>
        Friend Shared ReadOnly Property locaFileInput() As String
            Get
                Return ResourceManager.GetString("locaFileInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;content contentuid=&quot;UUIDhandle&quot; version=&quot;1&quot;&gt;OPTION_NAME&lt;/content&gt;.
        '''</summary>
        Friend Shared ReadOnly Property locaSnippetInput() As String
            Get
                Return ResourceManager.GetString("locaSnippetInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property locked_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("locked_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;save&gt;
        '''	&lt;version major=&quot;4&quot; minor=&quot;0&quot; revision=&quot;6&quot; build=&quot;5&quot; /&gt;
        '''	&lt;region id=&quot;MaterialBank&quot;&gt;
        '''		&lt;node id=&quot;MaterialBank&quot;&gt;
        '''			&lt;children&gt;
        '''		
        '''			&lt;!-- =======================Horn Material====================== --&gt;
        '''			MERGED_MATERIAL_SNIPPET
        '''			&lt;/children&gt;
        '''		&lt;/node&gt;
        '''	&lt;/region&gt;
        '''	&lt;region id=&quot;TextureBank&quot;&gt;
        '''		&lt;node id=&quot;TextureBank&quot;&gt;
        '''			&lt;children&gt;
        '''
        '''			&lt;!-- ==================Horn Textures======================= --&gt;
        '''			MERGED_TEXTURES_SNIPPET
        '''			
        '''			&lt;/children&gt;
        '''		&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property mergedFileInput() As String
            Get
                Return ResourceManager.GetString("mergedFileInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 			&lt;!-- ======================= UUIDhandle ====================== --&gt;
        '''			&lt;node id=&quot;Resource&quot;&gt;
        '''					&lt;attribute id=&quot;DiffusionProfileUUID&quot; type=&quot;FixedString&quot; value=&quot;&quot; /&gt;
        '''	&lt;!-- Referenced in VisualBank as the MaterialID  --&gt;
        '''					&lt;attribute id=&quot;ID&quot; type=&quot;FixedString&quot; value=&quot;MATERIAL_UUID&quot; /&gt;
        '''					&lt;attribute id=&quot;MaterialType&quot; type=&quot;uint8&quot; value=&quot;18&quot; /&gt;
        '''	&lt;!-- Horns texture file prefix  --&gt;
        '''					&lt;attribute id=&quot;Name&quot; type=&quot;LSString&quot; value=&quot;TEXTURE_PREFIX&quot; /&gt;
        '''	&lt;!-- This is the same for all horns, dont touch  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property mergedMaterialSnippetInput() As String
            Get
                Return ResourceManager.GetString("mergedMaterialSnippetInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 			&lt;!-- ========================= UUIDhandle ================================ --&gt;
        '''				
        '''			&lt;node id=&quot;Resource&quot;&gt;
        '''					&lt;attribute id=&quot;AttachBone&quot; type=&quot;FixedString&quot; value=&quot;&quot; /&gt;
        '''					&lt;attribute id=&quot;AttachmentSkeletonResource&quot; type=&quot;FixedString&quot; value=&quot;&quot; /&gt;
        '''					&lt;attribute id=&quot;BlueprintInstanceResourceID&quot; type=&quot;FixedString&quot; value=&quot;&quot; /&gt;
        '''	&lt;!-- Need to figure out where BoundsMax, BoundsMin, Center values come from --&gt;   				
        '''					&lt;attribute id=&quot;BoundsMax&quot; type=&quot;fvec3&quot; value=&quot;0.2241342 1.923792 0.08434314&quot; /&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property mergedMeshSnippetInput() As String
            Get
                Return ResourceManager.GetString("mergedMeshSnippetInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 			&lt;!-- ================== UUIDhandle ======================= --&gt;
        '''			
        '''&lt;!-- Physical Map --&gt;
        '''
        '''&lt;node id=&quot;Resource&quot;&gt;
        '''					&lt;attribute id=&quot;Depth&quot; type=&quot;int32&quot; value=&quot;1&quot; /&gt;
        '''					&lt;attribute id=&quot;Height&quot; type=&quot;int32&quot; value=&quot;1024&quot; /&gt;
        '''	&lt;!-- Referenced in MaterialBank --&gt;				
        '''					&lt;attribute id=&quot;ID&quot; type=&quot;FixedString&quot; value=&quot;PMAP_UUID&quot; /&gt;
        '''	&lt;!-- Match file name --&gt;
        '''					&lt;attribute id=&quot;Name&quot; type=&quot;LSString&quot; value=&quot;TEXTURE_PREFIX_PM&quot; /&gt;
        '''					&lt;attribute id=&quot;SRGB&quot; type=&quot;bool&quot; value=&quot;False&quot; /&gt;
        '''	&lt;!-- Texture file  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property mergedTextureSnippetInput() As String
            Get
                Return ResourceManager.GetString("mergedTextureSnippetInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;save&gt;
        '''  &lt;version major=&quot;4&quot; minor=&quot;0&quot; revision=&quot;0&quot; build=&quot;49&quot;/&gt;
        '''  &lt;region id=&quot;Config&quot;&gt;
        '''    &lt;node id=&quot;root&quot;&gt;
        '''      &lt;children&gt;
        '''        &lt;node id=&quot;Dependencies&quot;/&gt;
        '''        &lt;node id=&quot;ModuleInfo&quot;&gt;
        '''          &lt;attribute id=&quot;Author&quot; type=&quot;LSWString&quot; value=&quot;AUTHOR_NAME&quot;/&gt;
        '''          &lt;attribute id=&quot;CharacterCreationLevelName&quot; type=&quot;FixedString&quot; value=&quot;&quot;/&gt;
        '''          &lt;attribute id=&quot;Description&quot; type=&quot;LSWString&quot; value=&quot;MOD_DESC&quot;/&gt;
        '''          &lt;attribute id=&quot;Folder&quot; type=&quot;LSWS [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property metaSnippetInput() As String
            Get
                Return ResourceManager.GetString("metaSnippetInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property unlocked_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unlocked_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
